resolver: lts-18.10
allow-newer: true

packages:
- '.'

extra-deps:
  - git: https://github.com/incoherentsoftware/sdl2.git
    commit: 23b01fc60284565e581bcc6e2b1c679ef9007f8c
  - git: https://github.com/incoherentsoftware/sdl2-image.git
    commit: ab036e1c91e3cf5fcc89d3d61bd6c2e975c2f38d
  - git: https://github.com/incoherentsoftware/sdl2-ttf.git
    commit: 80962161bd512890d5eeea26f1bdc48a530da1af
  - directory-1.3.6.2
  - hashable-1.3.0.0
  - integer-logarithms-1.0.3.1
  - scientific-0.3.7.0
  - text-1.2.4.1
  - time-1.9.3

flags:
  sdl2:
    no-linear: true

extra-package-dbs: []
